# Generated by Django 5.2.8 on 2025-12-05 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_saver', '0002_alter_anagrams_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anagrams',
            options={'verbose_name_plural': 'Anagrams'},
        ),
    ]
