# Generated by Django 5.2.8 on 2025-12-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_saver', '0003_alter_anagrams_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anagrams',
            name='anagram',
        ),
        migrations.AddField(
            model_name='anagrams',
            name='anagrams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anagrams',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
