# Generated by Django 5.2.8 on 2026-02-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_saver', '0004_remove_anagrams_anagram_anagrams_anagrams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anagrams',
            name='create_date',
            field=models.DateField(default='2026-02-13'),
        ),
    ]
